name: Input or GITHUB_REF name
description: Returns either the name given via input or parses it from GITHUB_REF
author: AlmirKadric

# branding:
#     icon:
#     color:

inputs:
    input-key:
        description: The input key to check before trying to parse `name` from `GITHUB_REF`.
        default: target-ref

outputs:
    ref:
        description: The resulting raw ref
        value: ${{ steps.get-ref.outputs.ref }}
    ref-name:
        description: Resulting ref name
        value: ${{ steps.get-ref.outputs.refName }}

runs:
    using: composite
    steps:
        - id: get-ref
          shell: bash
          env:
            INPUT_REF: ${{ github.event.inputs[inputs.input-key] }}
          run: |
            if [ -n "${INPUT_REF}" ]; then
                echo ::set-output name=ref::$(echo ${INPUT_REF})
                echo ::set-output name=ref-name::$(echo ${INPUT_REF})
            else
                echo ::set-output name=ref::$(echo ${GITHUB_REF})
                echo ::set-output name=ref-name::$(echo ${GITHUB_REF#refs/*/})
            fi
