name: Node.js Subsystem Setup
description: Initial boilerplate setup for a Node.js subsystem project
author: AlmirKadric

# branding:
#     icon:
#     color:

inputs:
    input-key:
        description: >
            The target ref input key for the job. This defaults to 'target-ref'
            if not provided.

            ※ This is a proxy to the `input-key` input for the `catalyst-stack/github-actions/input-or-ref-name` action.
        default: target-ref
    node-version:
        description: >
            Node.js version to setup. This defaults to '14' if not provided.

            ※ This is a proxy to the `node-version` input for the `actions/setup-node` action.
        default: '14'
    git-ref:
        description: >
            Git reference to checkout. This defaults to the input target ref if
            provided or the SHA/ref of the event which triggered the job.

            ※ This is a proxy to the `ref` input for the `actions/checkout` action.
        default: null
    cache-key:
        description: >
            Unique key identity for saving and restoring to and from the cache.
            The `${{ runner.os }}-deps-${{ hashFiles('**/package-lock.json') }}`
            default will be used if not provided.

            ※ This is a proxy to the `key` input for the `actions/cache` action.
        default: ${{ runner.os }}-deps-${{ hashFiles('**/package-lock.json') }}
    cache-path:
        description: >
            Newline seperated list of path(s) which should be cached. This
            defaults to `./node_modules` if not provided.

            ※ This is a proxy to the `path` input for the `actions/cache` action.
        default: |
            ./node_modules

outputs:
    ref:
        description:
        value: ${{ steps.get-ref.outputs.ref }}
    ref-name:
        description:
        value: ${{ steps.get-ref.outputs.ref-name }}
    cache-hit:
        description:
        value: ${{ steps.dep-cache.outputs.cache-hit }}

runs:
    using: composite
    steps:
        # Determine target ref & name from input value or by parsing GITHUB_REF
        - id: get-ref
          name: 'Determine target git ref'
          if: inputs.git-ref == null
          uses: catalyst-stack/github-actions/input-or-ref-name@master
          with:
            input-key: ${{ inputs.input-key }}

        # Setup node.js v14
        - name: 'Setup Node.js'
          uses: actions/setup-node@v2
          with:
            node-version: ${{ inputs.node-version }}
            check-latest: true

        # Checkout repository under ${GITHUB_WORKSPACE}
        # NOTE: this will eithr checkout given
        - name: 'Checkout repository'
          uses: actions/checkout@v2
          with:
            ref: ${{ inputs.git-ref || steps.get-ref.outputs.ref || null }}

        # Setup dependency caching
        - id: dep-cache
          name: 'Setup dependency cache'
          uses: actions/cache@v2
          with:
            key: ${{ inputs.cache-key }}
            path: ${{ inputs.cache-path }}
